### ISSUE TITLE
无法调用sui

### ISSUE THREAD

**Issue by wentywenty** [BinTianqi/OwnDroid#10]
设备没有安装shizuku，但是安装了sui，但是无法调用
设备环境：
MIUI PAD14.0.9
Ksu11682 LKM
![IMG_20240419_165310.jpg](https://github.com/BinTianqi/AndroidOwner/assets/63338034/ae288888-6c64-44a1-8c98-ef428e284851)

**Comment by BinTianqi** [comment]
[使用指南](https://github.com/BinTianqi/AndroidOwner/blob/master/Guide.md?plain=1#L165)

[Shizuku-API](https://github.com/RikkaApps/Shizuku-API)学习成本太高了，我学不会。shizuku相关功能是套壳的rish，所以不支持sui

以后会支持的

（你都有root了，就用终端模拟器自己敲激活命令吧）

**Comment by BinTianqi** [comment]
[owndroid-shizuku-fix.zip](https://github.com/BinTianqi/OwnDroid/files/15071930/owndroid-shizuku-fix.zip)

@wentywenty 试试这个

**Comment by wentywenty** [comment]
安装app，点击app中的shizuku按钮后，它在一次又一次地弹出sui的授权窗口

**Comment by wentywenty** [comment]
视频太大了，上传不了

**Comment by wentywenty** [comment]
![1000002578.mp4.zip](https://github.com/BinTianqi/OwnDroid/files/15079177/1000002578.mp4.zip)

ok传上去了

**Comment by BinTianqi** [comment]
你可以先在sui里授权之后再打开owndroid，应该能用。这个问题今天中午修

（我每200ms检测shizuku权限，在shizuku上的行为是不会弹窗）

**Comment by wentywenty** [comment]
感谢。辛苦了

**Comment by BinTianqi** [comment]
好了
