### ISSUE TITLE
[Enhancement] Add help dialog for users migrating from old versions

### ISSUE THREAD

**Issue by MinoriceOwO** [BinTianqi/OwnDroid#11]
## 描述问题 / Describe the issue
OwnDroid 在刚刚的更新中修改了包名 (`com.binbin.androidowner` --> `com.bintianqi.owndroid`)。授予了旧版本应用 Device owner 权限的用户需要手动将旧版本应用上的权限迁移至新版本应用上。部分用户可能不知道具体如何操作 (例如可能有部分用户在激活后再也没有点进顶部的 "已激活" 的权限管理入口, 同时他们大概也不会去翻用户指南)。这可能造成不必要的 Issues 出现, 部分用户甚至可能会尝试通过 adb 先禁用旧应用的 Device owner 权限, 再手动删除设备上所有用户和账户后, 使用 adb 将 Device owner 权限授予新应用。这将会造成完全不必要的用户和账户数据丢失, 并且带来许多麻烦。

## 预期结果 / Expected result
建议在短期之内 (例如一个大版本号之内, 5.X 中) 为 OwnDroid 添加旧版本迁移检测。OwnDroid 首次启动时会检测设备的 Device owner 是否被设为了旧版本应用 (或者说, 如果无 Shizuku 权限情况下没有这种 API 的话, 那么就检测旧版本应用的包名是否存在于 Package Manager 列表中)。如果是, OwnDroid 就会向用户展示一个帮助提示框, 告知用户可以通过 OwnDroid 的 "转移 Device owner 所有权" 的功能以直接迁移至新版本。

## 建议的实现方案 / Advised implement
· 直接添加一个对话框。
· 或是单独添加一个引导页面, 首次启动时符合条件则提示用户是否前往查看引导页面。

## 额外信息 / Additional information
同时最好在引导末尾建议用户迁移完成后重启设备, 否则可能即使卸载了旧版本 OwnDroid, 也会在设备管理器页面看到有两个 OwnDroid 都被激活为 Device admin。(影响未知, 但看着难受)

## 版本信息 / Version
OwnDroid 版本: `v5.0-preview2`

**Comment by BinTianqi** [comment]
我release [v5.0正式版](https://github.com/BinTianqi/OwnDroid/releases/tag/v5.0)了

去下载的人应该都能看到那个迁移说明

**Comment by BinTianqi** [comment]
你用的时候觉得“已激活”可以点击吗？

**Comment by MinoriceOwO** [comment]
> 你用的时候觉得“已激活”可以点击吗？

啊, 我第一次用的时候就觉得可以。不过这个好像确实不是特别常见的交互设计, LSPosed 里的"已激活"就点不了。或许可以在"已激活"的右边加一个白色小箭头来提示用户...?

**Comment by BinTianqi** [comment]
我也是觉得这个东西让人看起来觉得点不了，我以前加过一个箭头，又有点奇怪

在未激活的时候加一行小字“点击查看”，这样就让人知道这个可以点击了

**Comment by MinoriceOwO** [comment]
> 我也是觉得这个东西让人看起来觉得点不了，我以前加过一个箭头，又有点奇怪
> 
> 在未激活的时候加一行小字“点击查看”，这样就让人知道这个可以点击了

合理了不少。
为了更明显一些, 或许可以为首次启动的用户添加一个聚焦提示, 就像这样:
![Pres1.png](https://s2.loli.net/2024/04/21/FqQNAxnjRYv5d6s.png)

**Comment by MinoriceOwO** [comment]
> 我release [v5.0正式版](https://github.com/BinTianqi/OwnDroid/releases/tag/v5.0)了
> 
> 去下载的人应该都能看到那个迁移说明

迁移说明中的方案似乎不是最佳方案。实际上使用 OwnDroid 的"迁移所有权"功能就能直接转移 Device owner 权限, 不需要撤销后再激活一次。

**Comment by BinTianqi** [comment]
哦对，忘了这个功能了😂

你试过吗？

**Comment by MinoriceOwO** [comment]
> 哦对，忘了这个功能了😂
> 
> 你试过吗？

迁移的时候试过了, 是能用的 =w=
