### ISSUE TITLE
app crash when I click to open password complexity

### ISSUE THREAD

**Issue by SplatHenry** [BinTianqi/OwnDroid#15]
Hello! I'm experiencing app crash when I click to open password complexity in the settings for key guard and password. I have a Z Fold5 using Android 14 at a 34 API level with One UI 6.1 as my UI and I've used Shizuku to gain most of my privileged access so far and I'd like for your app to give me a little more access. Thanks for any help or feedback you can give me!

**Comment by BinTianqi** [comment]
## I need log

1. Install [LogFox](https://github.com/F0x1d/LogFox/releases/download/v1.5.7/logfox-1.5.7.apk), grant Shizuku permission to it. 
2. Reproduce this bug, LogFox will send a notification when app crash. 
3. Send logs here.

**Comment by BinTianqi** [comment]
## I can use this function

Redmi Note 7 pro, lineageOS 21(API34). 

Device owner is activated. 

![OwnDroid](https://github.com/BinTianqi/OwnDroid/assets/146811279/3fb5b8f9-54d5-489f-94e8-e77d3cd06a0b)

**Comment by BinTianqi** [comment]
Resolved?

**Comment by Minoricew** [comment]
### This Issue is out-of-date.
Since there aren't any new replies to the issue for a long duration, we assume that your issue has been resolved. If the issue persists, please reopen the issue and provide a detailed problem description & your error logs.
