### ISSUE TITLE
Cannot remove work profile. 

### ISSUE THREAD

**Issue by Xisrr1** [BinTianqi/OwnDroid#16]
There is no way to delete the work profile because the app crashes when trying to do so.

**Comment by BinTianqi** [comment]
I'm sorry to hear that. 

This bug should be fixed in 57e5021 ,  you can try [v5.1 release](https://github.com/BinTianqi/OwnDroid/releases/tag/v5.1). 

If you don't want to update, type some text in the "Reason" textfield.

**Comment by Xisrr1** [comment]
> I'm sorry to hear that. 
> 
> This bug should be fixed in 57e5021 ,  you can try [v5.1 release](https://github.com/BinTianqi/OwnDroid/releases/tag/v5.1). 
> 
> If you don't want to update, type some text in the "Reason" textfield. 

When I tried to disable the profile owner feature it crashed. I've already factory reset my device. Please make sure it's well optimized before publishing such a powerful app. Also, the app is freezing whenever you click the back button.

**Comment by BinTianqi** [comment]
You cannot disable a profile owner on a work peofile. If you want to remove a work profile, please go to `System manager -> Wipe data`, you can remove work profile there.

**Comment by Xisrr1** [comment]
So it will remove only the work profile?

**Comment by BinTianqi** [comment]
yeah, data of the system user will not be removed

**Comment by Xisrr1** [comment]
I've already performed a factory reset but it is good to know. Can you fix the lag in the app when going back?

**Comment by BinTianqi** [comment]
You can feel the lag, possibly due to the mismatch between the fade out animation and the slide animation. 

I will fix it.

**Comment by Xisrr1** [comment]
Thanks

Also, is it possible to change the design of the app suspended popup? Like to add a button with another custom option.

**Comment by BinTianqi** [comment]
I optimized the animation (e19a9be2f7b48875409d0fa1e82376a44337af14), the lag should be reduced. 


> Also, is it possible to change the design of the app suspended popup? Like to add a button with another custom option.

What do you mean?  Do you mean OwnDroid itself or OwnDroid suspend other apps in _App manager_ section?

**Comment by BinTianqi** [comment]
> When suspending an app and trying to open this app, it will show "action not allowed" and an "OK" button. I want to be able to add another option besides the OK button with a custom function. For example, "enter password" button so you can unsuspend the app.

I tried to open a suspended app and Android system showed me a dialog. 

> ###             Can't open this app
>
>If you have questions, contact your IT admin
>
>**[  Learn more  ]**             **[  OK  ]**

Do you mean this?

**Comment by Xisrr1** [comment]
Yes. I tried using Google parental controls and when trying to open a suspended app, it will show a different popup with actions from the parental controls. I don't know if it's possible but I will ask.

**Comment by BinTianqi** [comment]
this dialog is sent by Android system, OwnDroid can't modify it.

**Comment by Xisrr1** [comment]
Thanks.

Do you know if Samsung Knox is more powerful than device/profile owner?

**Comment by BinTianqi** [comment]
Knox will be unavailable after bootloader unlocked. This is the only thing I know about Knox. 

I don't touch any Samsung device since 2005😂

**Comment by Xisrr1** [comment]
Ah okay.
So when is the update coming?

**Comment by BinTianqi** [comment]
In a week
