### ISSUE TITLE
[Feature Request] Permissions

### ISSUE THREAD

**Issue by CamsShaft** [BinTianqi/OwnDroid#18]
Me again. For these permissions pictured here, are they revoked just because it's not a trusted app like if it was Knox or some other mdm app or is there something missing in the manifest? I'm just curious if we can add anything in particular to the manifest for elevated privileges like "android.uid.system". Basically I'd like to actually run this as system like it says "system user: true"  in the user info section. Being able to integrate a debug version to utilize run-as would be great too. I know it's probably a lot and don't worry about it if you're not able to. I don't have enough knowledge to try "modding" it myself and if I did it would be just for me but would always give credit if I figured something out anyways. Again, please don't take any of that the wrong way and if it's any trouble just let me know. Thank you! 
![Screenshot_20240507_094804_AM Debug](https://github.com/BinTianqi/OwnDroid/assets/141678661/5534aca2-319e-4493-924d-51ce293b5b8a)

**Comment by BinTianqi** [comment]
**Good idea!** 

These permissions are useless at the moment because they cannot be granted in normal ways, not even by ADB or Root. To grant these permissions, OwnDroid must be installed as a system app. When OwnDroid becomes a system application and has these permissions, some functions can be used without activating the Device owner.

I am planning on it.

**Comment by CamsShaft** [comment]
Thanks for the reply :) 
    That's great to hear, I've been trying to learn more about sharedUser android.uid.system and finally found a good chatbot that won't censor itself when it comes to sensitive information so that will be a big help in hopefully getting some elevated privileges. Android 14 has been a nightmare with restrictions, can't even copy from /Android/data anymore (nothing I've found anyways.) Thanks again and hope tossing some ideas around can be helpful in the long run.

**Comment by Johngithubandroidpc** [comment]
Hello, I'd like to know how to safely uninstall both the Shizuku and OwnDroid apps, and reinstall them afterwards. Currently, I'm facing constant pop-ups with "com.android.phone has stopped" and "com.android.system.UI has stopped," and I need to resolve this issue. Luckily I can connect my phone to my computer through Adb commands now. Thank you

**Comment by BinTianqi** [comment]
Uninstall shizuku: 
```bash
pm uninstall moe.shizuku.privileged.api
```

Uninstall OwnDroid, it works only when OwnDroid isn't device owner
```bash
pm uninstall com.bintianqi.owndroid
```

**Comment by Johngithubandroidpc** [comment]
I apologize; I meant to say Dhizuku instead of Shizuku. I did create a new discussion topic, but I'm not sure if you can see it. So this will be my final question here. Thank you very much!

> Uninstall shizuku: 
> ```bash
> pm uninstall moe.shizuku.privileged.api
> ```
> 
> Uninstall OwnDroid, it works only when OwnDroid isn't device owner
> ```bash
> pm uninstall com.bintianqi.owndroid
> ```
> 
> By the way, if you still cannot solve this problem, please create a [discussion](https://github.com/BinTianqi/OwnDroid/discussions), because your question is not related to this issue.

**Comment by BinTianqi** [comment]
Those permissions started with "MANAGE_DEVICE_POLICY_" are internal permissions. OwnDroid can't get these permissions unless OwnDroid is ran in uid 1000(system). Install OwnDroid as system app won't work. System apps under /system/app or privileged system apps under /system/priv-app aren't ran in uid 1000.
sharedUser requires OwnDroid's signature is the same as system signature.
