### ISSUE TITLE
Delete Owndroid

### ISSUE THREAD

**Issue by echov1b1t** [BinTianqi/OwnDroid#21]
I'm having trouble deleting owndroid because I can't delete owndroid's work profile, I'm on Xiaomi device

**Comment by BinTianqi** [comment]
You created a work profile and you can't remove it? 

Go to "System manager -> Wipe data" in OwnDroid **in work profile**, after you press "Wipe data" button, you work profile will be removed.

**Comment by echov1b1t** [comment]
Thanks
