### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by fyhbauyg** [BinTianqi/OwnDroid#24]
[com.bintianqi.owndroid_2024-05-23T22_09_44.558.log](https://github.com/BinTianqi/OwnDroid/files/15424546/com.bintianqi.owndroid_2024-05-23T22_09_44.558.log)

**Comment by MinoriceOwO** [comment]
> [com.bintianqi.owndroid_2024-05-23T22_09_44.558.log](https://github.com/BinTianqi/OwnDroid/files/15424546/com.bintianqi.owndroid_2024-05-23T22_09_44.558.log)

似乎是在获取当前密码已失败数据时遇到的权限不足异常。能否提供进一步的信息 (包括 OwnDroid 权限授予状态等) 以便更好地定位问题?

**Comment by BinTianqi** [comment]
还好这是v5.2。v5.3我开了混淆，但是又没保存proguard mapping

**Comment by fyhbauyg** [comment]
> > [com.bintianqi.owndroid_2024-05-23T22_09_44.558.log](https://github.com/BinTianqi/OwnDroid/files/15424546/com.bintianqi.owndroid_2024-05-23T22_09_44.558.log)
> 
> 似乎是在获取当前密码已失败次数时遇到的权限不足异常。能否提供进一步的信息 (包括 OwnDroid 权限授予状态、问题复现过程等) 以便更好地定位问题?

已经知道问题，我使用xposed模块dax使用共享设备管理员接口而dhizuku没后台所以崩溃。

**Comment by Minoricew** [comment]
超长弧 Issue。
@BinTianqi Issue resolved.
