### ISSUE TITLE
English translation inside the app

### ISSUE THREAD

**Issue by Gamer750** [BinTianqi/OwnDroid#3]

**Comment by HAX05** [comment]
I set the Language in res/xml/backup_rules.xml from "zh-CN" to "en" but App Language always Chinese how to Change the Language?

**Comment by BinTianqi** [comment]
This app currently does not support English, I will translate it as soon as possible.

**Comment by CamsShaft** [comment]
I used an app specifically made to translate the strings.xml. it's called stringsXML translator. Just follow the instructions, it's very easy to use.

**Comment by HAX05** [comment]
> This app currently does not support English, I will translate it as soon as possible.
> 
> Translation contributors are welcome.

Ahhh.. nevermind :)  
I'm importing the whole Project in Android Studio and the IDE translate it now its all in english 👍 

Thanks for youre Project!
