### ISSUE TITLE
App lock

### ISSUE THREAD

**Issue by randomid7** [BinTianqi/OwnDroid#30]
Sir,
Can you please introduce the feature of applying app lock with password on any android app with the help of permission of device owner.
As i am using the older version of android,i don't have the feature of app lock on my device.
Please, look into it for me.

**Comment by BinTianqi** [comment]
### No, I can't

This funtion is not included in Android's DevicePolicyManager API. So I won't introduce this feature. 

If you want to set app lock, you should find a third-party launcher that supports it.

> As i am using the older version of android,i don't have the feature of app lock on my device.

Unlike some deep-modified ROM, app lock in AOSP is a feature of launcher3, not system framework.
