### ISSUE TITLE
[Feature Request] Custom installer

### ISSUE THREAD

**Issue by nubesurrealista** [BinTianqi/OwnDroid#31]
Something that I liked was the possibility of installing applications silently, without confirmation from the package installer. I've used it a lot, is there any plan to make the app be set as the default installer?

**Comment by BinTianqi** [comment]
Currently you can't open a .apk file with this app, so you can't set this app as default installer

I will support this in the future

**Comment by nubesurrealista** [comment]
> I will support this in the future

I'll wait, thanks for the app, I love it!
