### ISSUE TITLE
[Feature Request] Automation Integration

### ISSUE THREAD

**Issue by chipzhang** [BinTianqi/OwnDroid#32]
Does it support Tasker plugin API, so that I can use it in tasker?
Or does it support shortcuts? So I can add shortcuts to desktop or other apps that supports running a shortcut?
So I can automate the available actions in this app.

**Comment by BinTianqi** [comment]
[ErfanRht/Tasker](https://github.com/ErfanRht/Tasker) This "Tasker" ?

This seems like a good idea.

**Comment by MinoriceOwO** [comment]
> This seems like a good idea.
> 
> But which "Tasker" did you mean? Can you give me a link to this program?

Seems to be [this one](https://tasker.joaoapps.com/index.html) I think, an automation tool for Android.

**Comment by chipzhang** [comment]
The link provided by MinoriceOwO is right.

Moreover, many other popular android automation tools (Automate, AutomateIt, Macrodroid) seems to support Tasker plugins, as far as I know.

**Comment by chipzhang** [comment]
Moreover, supporting command line usage (i.e. via Termux scripts) may be another choice for automation.

**Comment by BinTianqi** [comment]
Tasker is a proprietary software. I have to buy it after 7-day trial. So I won't support it.

I may support intent-based actions. Almost all automation apps can send intent. Termux script can send a intent too

**Comment by MinoriceOwO** [comment]
> Tasker is a proprietary software. I have to buy it after 7-day trial. So I won't support it.

u can use the [crack version](https://www.yxssp.com/25441.html) of Tasker though. 😆
 
> I may support intent-based actions. Almost all automation apps can send intent. Termux script can send a intent too

that's pretty a good idea.

**Comment by chipzhang** [comment]
> Tasker is a proprietary software. I have to buy it after 7-day trial. So I won't support it.

Some other popular automation apps is free (perhaps need pay for advanced pro features) and they support Tasker plugin as well.

As per [Automate official site](https://llamalab.com/automate/):
> [Automate](https://play.google.com/store/apps/details?id=com.llamalab.automate&referrer=utm_source%3Dhomepage) is a **free** app for Android...
> ...
> Easily integrate installed apps supporting the [Locale](https://www.twofortyfouram.com/)/[Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm) plug-in API

As per [Macrodroid official site](https://www.macrodroid.com/):
> Fully compatible with Tasker and Locale plugins
