### ISSUE TITLE
couldn't remove user id 10

### ISSUE THREAD

**Issue by KimetsuAndrea** [BinTianqi/OwnDroid#34]
after executing this command:

$ pm list users

Users:
        UserInfo{0:HOME (Jay):c13} running
        UserInfo{10:WORKPROFILE:1030} running

$ pm remove-user 10

Error: couldn't remove user id 10

**Comment by BinTianqi** [comment]
Resolved?

**Comment by KimetsuAndrea** [comment]
Bruh help me😭

**Comment by KimetsuAndrea** [comment]
I can't installed the modified apk file (OwnDriod, edited AndriodManifest.xml, TestOnly=true)

![Screenshot_20240607_172721.jpg](https://github.com/BinTianqi/OwnDroid/assets/127398030/15103916-da33-44c8-9488-2411f014be53)

**Comment by MinoriceOwO** [comment]
> I can't installed the modified apk file (OwnDriod, edited AndriodManifest.xml, TestOnly=true)

After you modified the APK, the file will not contain any valid signature so PackageManager won't let you install it. To solve this, try to sign the APK with testKey.

> after executing this command:
> 
> $ pm list users
> 
> Users: UserInfo{0:HOME (Jay):c13} running UserInfo{10:WORKPROFILE:1030} running
> 
> $ pm remove-user 10
> 
> Error: couldn't remove user id 10

The user with id 10 is a work profile. Are you using Island or other multi-app implementation? Maybe you should delete the work profile through these apps.

**Comment by KimetsuAndrea** [comment]
> > I can't installed the modified apk file (OwnDriod, edited AndriodManifest.xml, TestOnly=true)
> 
> Once the APK is modified, the file will not contain any valid signature so PackageManager won't let you install it. To resolve this, try signing the APK with testKey.
> 
>HOW?, I'm just a kid
>
> > after executing this command:
> > $ pm list users
> > Users: UserInfo{0:HOME (Jay):c13} running UserInfo{10:WORKPROFILE:1030} running
> > $ pm remove-user 10
> > Error: couldn't remove user id 10
> 
> The user with id 10 is a work profile. Are you using Island or other multi-app implementations? Maybe you should delete the work profile through these apps.
>
>OwnDriod: Actived Work Profile
![Screenshot_20240608_170756](https://github.com/BinTianqi/OwnDroid/assets/127398030/1fca121f-2a8e-4cd5-a3d1-119409c4228a)

**Comment by BinTianqi** [comment]
> INSTALL_FAILED_TEST_ONLY

Install OwnDroid with pm:
```shell
pm install /path/to/OwnDroid.apk -t
```

> OwnDriod: Actived Work Profile

Did you remove your previous work profile and create a new work profile with OwnDroid?

**Comment by KimetsuAndrea** [comment]
> > INSTALL_FAILED_TEST_ONLY
> 
> Install OwnDroid with pm:
> ```shell
> pm install /path/to/OwnDroid.apk -t
> ```
>
Thanks
> 
> > OwnDriod: Actived Work Profile
> 
> Did you remove your previous work profile and create a new work profile with OwnDroid?
Nope

**Comment by BinTianqi** [comment]
What's your purpose?

If you want to install my release APK, you should uninstall OwnDroid that currently installed.

**Comment by KimetsuAndrea** [comment]
Why I can't deactivate this feature:
![Screenshot_20240608_193053](https://github.com/BinTianqi/OwnDroid/assets/127398030/3e7c0499-cba1-4f4d-8ffd-c478c6435b25)

**Comment by KimetsuAndrea** [comment]
> What's your purpose?
> 
> If you want to install my release APK, you should uninstall OwnDroid that currently installed.
>
Ok bruh
> 
> If you want to remove user 10, go to OwnDroid in work profile, then open System Manager -> Wipe data. Then click wipe data, and your work profile will be removed

Thanks

**Comment by KimetsuAndrea** [comment]
Thanks guys, I love you all
