### ISSUE TITLE
[Feature Request] Support third-party Device Owner API

### ISSUE THREAD

**Issue by zhiyi03** [BinTianqi/OwnDroid#35]
这个应用很好，完全符合我的想法。很久之前我就在想，设备管理员虽然有很高的权限，但是目前市面上的应用好像并没有体现出他权限之高。直到我偶然间发现了这个应用，就发现这就是我理想中想要的应用，所有能够实现的全在这上面实现了。但是有个问题，就是能不能将这个管理员权限权限供其他应用使用，供给他们授权，像dhizuku那样。就比如说雹，installx，他们都可以通过dhizuku授权达到共享的目的。我开始想的是用dhizuku给owndroid授权，看了之前的议题，既然dhizuku它的api不太ok，那么owndroid可不可以也出一个共享管理员权限的功能，以便于让其他的软件可以使用管理员权限，从而代替dhizuku的功能😘😘😘

**Comment by BinTianqi** [comment]
看来让OwnDroid支持Dhizuku的需求很大啊……
我再仔细看看Dhizuku的文档吧

能不能让OwnDroid代替Dhizuku，这个我不知道，没看它的源码

OwnDroid很难把完整的Device owner或Profile owner权限共享给别的应用，因为这需要那些应用的开发者来适配，这不现实。
但是安卓提供了一些标准API，可以共享部分权限（比如挂起应用），这个功能计划在v6.0做好。做好之后，Dhizuku也可以把部分权限共享给OwnDroid

**Comment by zhiyi03** [comment]
其实也不一定要支持dhizuku，dhizuku虽然提供了共享权限的功能，但实际上却浪费了大部分的其他功能。像是雹仅仅借用了设备管理员的权限进行了挂起和隐藏的操作，installx仅仅借用了权限进行锁定管理器。他们使用的功能极少，也就是说owndroid只要把基础的挂起隐藏等权限共享就可以了，Delegated Scopes应该就可以做到。开发者适配的问题的话不怕，路铺好了慢慢的就有人走了🥰🥰🥰很期待6.0的版本。

还有就是给两个小提议，在应用管理那里隐藏了app后就找不到app了，恢复方法非常麻烦，但是可以像卸载后保留的应用那样子搞一个应用列表![Screenshot_20240610_102649_com.bintianqi.owndroid.jpg](https://github.com/BinTianqi/OwnDroid/assets/99712233/c4c4c36e-00a5-4941-8073-b0b10b81c254)还有就是应用选择器希望可以增加一个搜索框或者是按xx排序的功能这样子更方便选择应用。🤩🤩🤩

**Comment by SteveZMTstudios** [comment]
owndroid目前似乎处于“半支持”Dhizuku状态。
当使用LSPatch修补OwnDroid并使用DAX.apk作为模块时，它几乎工作。
除了少部分（如移除Device Owner权限和应用OTA更新）

（所以我猜适配工作这一进程也许并不那么复杂？）

**Comment by SteveZMTstudios** [comment]
![Screenshot_2024-08-06-17-12-50-874_com.bintianqi.owndroid.jpg](https://github.com/user-attachments/assets/cc95b5f7-972e-42a8-98e4-00ad7bda570e)

**Comment by BinTianqi** [comment]
@SteveZMTstudios OwnDroid已经支持Dhizuku了，但是还没有发布正式版，可以去 [GitHub Actions](https://github.com/BinTianqi/OwnDroid/actions) 或 [Telegram OwnDroid CI频道](https://t.me/owndroid_ci) 下载

**Comment by SteveZMTstudios** [comment]
> @SteveZMTstudios OwnDroid已经支持Dhizuku了，但是还没有发布正式版，可以去 [GitHub Actions](https://github.com/BinTianqi/OwnDroid/actions) 或 [Telegram OwnDroid CI频道](https://t.me/owndroid_ci) 下载
> 
> > 你的屏幕截图里面那个“验证”会一直显示吗？还是你截图太快了？

好的，谢谢

> 不快点截图那个toast就消失力（
