### ISSUE TITLE
[Feature Request] Lock task

### ISSUE THREAD

**Issue by lyyh0** [BinTianqi/OwnDroid#36]
在testdpc中，有个Lock tesk的功能，可以很快固定应用，希望能加这个功能
（主要原因是testdpc太耗cpu了，打个dax模块就卡的要命，不好用
（加功能后兼不兼容dax我不强求，能多一个希望就行了💦💦💦

**Comment by BinTianqi** [comment]
你想说的是Lock task吗？

**Comment by lyyh0** [comment]
![Uploading Screenshot_2024-06-10-17-42-51-802_com.lbe.security.miui.jpg…]()

**Comment by lyyh0** [comment]
![Screenshot_2024-06-10-17-42-51-802_com lbe security miui](https://github.com/BinTianqi/OwnDroid/assets/80589217/ecbcbe13-012f-494c-96e4-fb714b725b36)

**Comment by adxpcc** [comment]
> testdpc
您这边使用testdpc主要是应用在什么场景啊?

**Comment by BinTianqi** [comment]
> 您这边使用testdpc主要是应用在什么场景啊?

🤔🤔🤔~~公司设备管理场景~~

**Comment by adxpcc** [comment]
> > 您这边使用testdpc主要是应用在什么场景啊?
> 
> 🤔🤔🤔~公司设备管理场景~

基于单机版的app来做设备管理吗?

**Comment by lyyh0** [comment]
> > testdpc
> > 您这边使用testdpc主要是应用在什么场景啊?

满足好奇心的情况下（）
