### ISSUE TITLE
Can't uninstall work profile 

### ISSUE THREAD

**Issue by JokanderTest** [BinTianqi/OwnDroid#39]
To be honest i installed this app without completely understand it's functionality...
But now i can see it created a new admin profile that cloned apps and made me unable to remove the profile nor application itself...
Kindly i need support to uninstall the app and profile.
Thank in advance

**Comment by BinTianqi** [comment]
I'm sorry that thers isn't a user guide in English.

1. Open OwnDroid **in work profile**
2. Open system manager -> wipe data
3. Confirm to wipe data
4. Your work profile is now removed

**Comment by BinTianqi** [comment]
Resolved?

Please close this issue after you resolved it

**Comment by Minoricew** [comment]
### This Issue is out-of-date.
Since there aren't any new replies to the issue for a long duration, we assume that your issue has been resolved. If the issue persists, please reopen the issue and provide a detailed problem description & your error logs.
