### ISSUE TITLE
Error 255 while trying to grant profile and device owner 

### ISSUE THREAD

**Issue by gghelix** [BinTianqi/OwnDroid#40]
when trying to grant profile or divice owner thru pc or shizuku error 255 pops up please help

**Comment by BinTianqi** [comment]
https://owndroid.pages.dev/Permission.html#device-owner
https://owndroid.pages.dev/FAQ.html#activating

They may help you

**Comment by BinTianqi** [comment]
Resolved?

Close this issue after your resolve it.

**Comment by mujul** [comment]
> https://owndroid.pages.dev/Permission.html#device-owner https://owndroid.pages.dev/FAQ.html#activating
> 
> They may help you

Please specify which commamds to execute in ashell in order to remove accounts.

**Comment by BinTianqi** [comment]
> How to remove accounts after typing "dumpsys account" in ashell.

Go to Settings -> Accounts -> *Account*(for example, Gmail) -> Remove account

> Do i have to manually add all the removed accounts after i wipe the work profile?

No.

**Comment by Minoricew** [comment]
### This Issue is out-of-date.
Since there aren't any new replies to the issue for a long duration, we assume that your issue has been resolved. If the issue persists, please reopen the issue and provide a detailed problem description & your error logs.
