### ISSUE TITLE
[Question] Error while granting device owner and device profile 

### ISSUE THREAD

**Issue by Coinwillwin** [BinTianqi/OwnDroid#41]
It just doesn't let me

**Comment by Coinwillwin** [comment]
And when I execute them shizuku turns off

**Comment by Coinwillwin** [comment]
Give error 255

**Comment by Coinwillwin** [comment]
It says device admin 2 
How do I disable them

**Comment by BinTianqi** [comment]
Go to settings -> Security -> More security -> Device admin apps

You can see all device admins there

**Comment by Coinwillwin** [comment]
I disabled but the device owner and device profile thing says error 255

**Comment by BinTianqi** [comment]
Then, check your accounts

If there are any accounts on your device, your can't activate Device owner

**Comment by Coinwillwin** [comment]
It gives me 
font color=#FF0000></font>
<font color=#FF0000>Exception occurred while executing 'set-profile-owner':</font>
<font color=#FF0000>java.lang.IllegalStateException: Not allowed to set the profile owner because there are already some accounts on the profile</font>
<font color=#FF0000>	at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetProfileOwnerLocked(DevicePolicyManagerService.java:9428)</font>
<font color=#FF0000>	at com.android.server.devicepolicy.DevicePolicyManagerService.setProfileOwner(DevicePolicyManagerService.java:8772)</font>
<font color=#FF0000>	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.runSetProfileOwner(DevicePolicyManagerServiceShellCommand.java:286)</font>
<font color=#FF0000>	at com.android.server.devicepolicy.DevicePolicyManagerServiceShellCommand.onCommand(DevicePolicyManagerServiceShellCommand.java:91)</font>
<font color=#FF0000>	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)</font>
<font color=#FF0000>	at android.os.ShellCommand.exec(ShellCommand.java:38)</font>
<font color=#FF0000>	at com.android.server.devicepolicy.DevicePolicyManagerService.onShellCommand(DevicePolicyManagerService.java:9831)</font>
<font color=#FF0000>	at android.os.Binder.shellCommand(Binder.java:954)</font>
<font color=#FF0000>	at android.os.Binder.onTransact(Binder.java:837)</font>
<font color=#FF0000>	at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:6969)</font>
<font color=#FF0000>	at android.os.Binder.execTransactInternal(Binder.java:1200)</font>
<font color=#FF0000>	at android.os.Binder.execTransact(Binder.java:1147)</font>

**Comment by BinTianqi** [comment]
Go to Settings -> Accounts -> *gmail* (for example) -> Remove account

You should remove all accounts before you activate profile owner or device owner

**Comment by Coinwillwin** [comment]
I did that but still it didn't let me
There is 1 account but it doesn't let me remove it

**Comment by BinTianqi** [comment]
What's the name of that account?

**Comment by Minoricew** [comment]
> I did that but still it didn't let me There is 1 account but it doesn't let me remove it

If you're having some trouble removing a specific account, try going to the app which created it to delete the account manually.

If the issue persists, please provide further information (screenshots, error logs, ...).

**Comment by Coinwillwin** [comment]
Lmao so weird situation I pressed wipe SD card
And it wiped my data lololol

**Comment by Coinwillwin** [comment]
> > I did that but still it didn't let me There is 1 account but it doesn't let me remove it
> 
> If you're having some trouble removing a specific account, try going to the app which created it to delete the account manually.
> 
> or just use `pm disable` to disable target app / use [HookDPM](https://github.com/BinTianqi/HookDPM) to bypass the limit.
> 
> If the issue persists, please provide further information (screenshots, error logs, ...).

So the problem is
There's no app for it but the name is Infinix id

**Comment by Coinwillwin** [comment]
Lemme try and log out

**Comment by Coinwillwin** [comment]
> > I did that but still it didn't let me There is 1 account but it doesn't let me remove it
> 
> If you're having some trouble removing a specific account, try going to the app which created it to delete the account manually.
> 
> or just use `pm disable` to disable target app / use [HookDPM](https://github.com/BinTianqi/HookDPM) to bypass the limit.
> 
> If the issue persists, please provide further information (screenshots, error logs, ...).

Umm I don't have root

**Comment by Coinwillwin** [comment]
> > > I did that but still it didn't let me There is 1 account but it doesn't let me remove it
> > 
> > If you're having some trouble removing a specific account, try going to the app which created it to delete the account manually.
> > 
> > or just use `pm disable` to disable target app / use [HookDPM](https://github.com/BinTianqi/HookDPM) to bypass the limit.
> > 
> > If the issue persists, please provide further information (screenshots, error logs, ...).
> 
> So the problem is
> There's no app for it but the name is Infinix id

I logged out and it worked less fugin goooooo

**Comment by Coinwillwin** [comment]
It worked u can put it as solved
