### ISSUE TITLE
[Bug] Error while installing apps in v5.5

### ISSUE THREAD

**Issue by zhiyi03** [BinTianqi/OwnDroid#47]
在利用owndroid安装owndroid之后，再次安装其他应用会出现错误，安装界面弹出之后立刻闪回，不能进行正常安装，需要杀掉owndroid后台才能正常安装。

**Comment by BinTianqi** [comment]
可以复现

我用OwnDroid安装OwnDroid之后，再安装其他应用，看不到安装应用对话框，查看应用详情，强行停止按钮是灰色的，点不了。用系统安装器重新安装OwnDroid之后又可以用了

看日志没发现问题，不知道是什么导致的

**Comment by zhiyi03** [comment]
今天发现这个原来是更大的bug，我用owndroid安装任意第1款软件之后，第2款都不能进行正常安装，只能有先杀掉后台才能进行继续安装
