### ISSUE TITLE
[Bug] <UI> Issue with network settings

### ISSUE THREAD

**Issue by Coinwillwin** [BinTianqi/OwnDroid#51]
When I go into network > settings it's just blank help

**Comment by BinTianqi** [comment]
UI issue?
Please give me a screenshot

**Comment by Coinwillwin** [comment]
I think it's a ui glitch here you go tho ![Screenshot_20240717-231018.jpg](https://github.com/user-attachments/assets/025ca41d-b802-4213-a564-127c9a26204c)

**Comment by BinTianqi** [comment]
> When I go into network > settings it's just blank help

Did you mean Network -> Options ?

**Comment by Coinwillwin** [comment]
Yeah that screenshot was without shizuku , with shizuku it's the same

**Comment by Coinwillwin** [comment]
> > When I go into network > settings it's just blank help
> 
> Did you mean Network -> Options ?

Yeah

**Comment by BinTianqi** [comment]
Sorry, I can't reproduce this issue. I asked my friends to reproduce it, they said they can open this page.

**Comment by Coinwillwin** [comment]
But how does this page look like??

**Comment by Minoricew** [comment]
> But how does this page look like??

like this:
![1000022791](https://github.com/user-attachments/assets/c60be770-01a3-48c7-99c5-7900baf5ce8d)

**Comment by Coinwillwin** [comment]
> > But how does this page look like??
> 
> like this:
> ![1000022791](https://github.com/user-attachments/assets/c60be770-01a3-48c7-99c5-7900baf5ce8d)
> 

Oh thank you so much ∆∆
