### ISSUE TITLE
[Feature Request] Enchant permission manager

### ISSUE THREAD

**Issue by GreenMystic** [BinTianqi/OwnDroid#54]
problem:
allowing permission is corcern me as privacy enthusiast it can make any app collect my data 
(ex: call allow app to collect IMEI)
but in other hand some app might refuse to work if permission disabled 
or i might need app in some situation

Please consider following solution:
1. add bouncer one time permission
2. add more condition to when permission is granted or denied

condition proposal:
1. allow permission if app on foreground or background only
2. allow permission only if app have task in background (ex: playing audio in background)

thanks for reading and consideration developer 🙏

**Comment by BinTianqi** [comment]
> 1. add bouncer one time permission

The DevicePolicyManager API only provides 3 status of permission that can be set for a app by OwnDroid : granted, denied and default(decided by user)

> 2. add more condition to when permission is granted or denied
> 
> condition proposal:
> 
> 1. allow permission if app on foreground or background only
> 2. allow permission only if app have task in background (ex: playing audio in background)

DevicePolicyManager does not provide any API to add these conditions.

OwnDroid will not actively detect the behavior of the application and change the permissions based on these behaviors, which is not good for privacy and will consume more battery (DevicePolicyManager may not provide such an API either)

So, I think the implementation of this feature is impossible.

**Comment by BinTianqi** [comment]
Sorry, I won't work on these features. If you have any other bug report or feature request, please open a new issue.
