### ISSUE TITLE
增加Dhizuku api

### ISSUE THREAD

**Issue by chumoew** [BinTianqi/OwnDroid#60]
增加Dhizuku api后可以直接授权OwnDroid设备所有者权限，跳过OwnDroid本来的复杂激活过程。
[https://github.com/iamr0s/Dhizuku](dhizuku)

**Comment by Minoricew** [comment]
> 增加Dhizuku api后可以直接授权OwnDroid设备所有者权限，跳过OwnDroid本来的复杂激活过程。 [https://github.com/iamr0s/Dhizuku](dhizuku)

Duplicate #35
