### ISSUE TITLE
[Feature Request] Support all third party DPC API 

### ISSUE THREAD

**Issue by GreenMystic** [BinTianqi/OwnDroid#63]
problem:
you can't have more than 1 device owner apps despite how many apps need it 

Please consider following solution:
add support for using others app devices owner privilege not only limited to Dhizuku but at least almost all if possible 

reference:
[Island Open API](https://github.com/oasisfeng/island?tab=readme-ov-file#open-api)
[Insular Open API](https://gitlab.com/secure-system/Insular#open-api)

note:
ik and aware this is duplicate issues i just try to make refresh version of it
thanks for reading and consideration developer 🙏

**Comment by BinTianqi** [comment]
There are tens of functions in DevicePolicyManager API, but Island and Insular only provide a few of them. 

Island and Insular can't provide such a API that OwnDroid can communicate with Android system as their identity.

**Comment by BinTianqi** [comment]
> so you will only support Dhizuku?

yes

**Comment by BinTianqi** [comment]
> app like island icebox app freezer and so on didn't have enough privilege like you said earlier?

I don't know, I don't use them

This issue is about "3rd party DPC APIs". I decided that I won't support more DPC APIs except Dhizuku and I closed this issue. Please open another issue/discussion if you have another bug report/feature request/question
