### ISSUE TITLE
[Feature Request] Improve permission selection

### ISSUE THREAD

**Issue by zhiyi03** [BinTianqi/OwnDroid#64]
在进行权限管理的时候，选择了某个应用程序的某权限，如果快速选择权限（就是在第一张图的界面![Screenshot_2024-07-23-14-49-25-38_27f98cbba1c8b4f3dede46a209e2dd0a.png](https://github.com/user-attachments/assets/c9bb8f8a-c6ff-4a84-bb78-31c78f73d6a3)

快速点击两次某权限）就必定会退回到owndroid主界面，这是一个bug。

另外希望大大改一下权限管理的ui，![Screenshot_2024-07-23-14-49-25-38_27f98cbba1c8b4f3dede46a209e2dd0a.png](https://github.com/user-attachments/assets/503e6605-8f1b-4236-b4e0-eaf8b18121b9)

如果改成进入权限管理就是这个页面，然后点击权限就可以进行默认允许解决三个选项的操作会方便很多，像这个样子![Screenshot_2024-07-23-14-55-02-48_3ddfc6ffaa21e6a18dca37b5b72fe931.png](https://github.com/user-attachments/assets/bdaabce4-f412-42dd-9e9d-1084547ff5f2)

另外还有个问题就是某些权限好像不能修改，点击没有效果，比如说身体传感器

**Comment by BinTianqi** [comment]
> 某些权限好像不能修改，点击没有效果，比如说身体传感器

需要目标应用在AndroidManifest中声明相应的权限，OwnDroid才能修改授权状态
