### ISSUE TITLE
[Feature Request] Block Reset app preference

### ISSUE THREAD

**Issue by GreenMystic** [BinTianqi/OwnDroid#65]
Problem:
I don't want accidentally resetting all preference 

Solution:
Pls kindly add option to block resetting app preference 

Thanks for consideration developer 🙏

**Comment by BinTianqi** [comment]
Do you mean `Clear app storage`?

**Comment by BinTianqi** [comment]
There isn't any DevicePolicyManager API to block `Reset app preferences`. 

btw I think nobody will clear app preferences *accidently*
