### ISSUE TITLE
[Feature Request] allow install cert on work profile

### ISSUE THREAD

**Issue by GreenMystic** [BinTianqi/OwnDroid#66]
problem:
if i installing app that's need cert obviously it won't work but I can't install it on work profile meanwhile i need it there 

solution:
pls add feature to install cert on work profile if possible thanks

**Comment by BinTianqi** [comment]
CA cert management is already available in work profile. 
Do you mean installed cert not work?

**Comment by BinTianqi** [comment]
> is owndroid already able to install cert for work profile?

Yes, OwnDroid can install CA cert for work profile if OwnDroid is the profile owner of that work profile
