### ISSUE TITLE
[Vulnerability] Bad password storing practices

### ISSUE THREAD

**Issue by bakad3v** [BinTianqi/OwnDroid#73]
I noticed that you are storing automation key in plaintext in shared preferences. It's bad practice for storing passwords. Shared preferences possibly can be read by anyone who have root access. It's a good practice to store hash instead of password, and ideally computation of password hash must be a time consuming process. There are special [key derivation functions ](https://en.wikipedia.org/wiki/Key_derivation_function#Password_hashing) such as Argon2 created for this purpose. I implemented password hashing in this pull request. I used default parameters for Argon2, may be they must be changed.
https://github.com/BinTianqi/OwnDroid/pull/72

**Comment by bakad3v** [comment]
Also more complex checking for password strength required, password with length 6 is really weak.

**Comment by BinTianqi** [comment]
> Shared preferences possibly can be read by anyone who have root access.

Anyone who have root access can also write SharedPrefs. So, in my opinion, storing hashed automation key is futile.

> key with length 6 is really weak. And it will be nice to add random key generation function.

This is a good idea, I will add random key generation function. 20 bytes of automation key should be enough

**Comment by 1fexd** [comment]
> Anyone who have root access can also write SharedPrefs. So, in my opinion, storing hashed automation key is futile.

I think you could use the [Android KeyStore](https://developer.android.com/privacy-and-security/keystore#UsingAndroidKeyStore)

**Comment by bakad3v** [comment]
Yes, I also think using encrypted shared preferences may be a proper solution.

**Comment by BinTianqi** [comment]
As a user application, it is impossible to compete with root privilege.

So, all I have to do is prevent the key from being cracked by other user apps. I think a 20-digit key should be difficult enough to crack.
