### ISSUE TITLE
lost ability for multi user

### ISSUE THREAD

**Issue by RedMentos** [BinTianqi/OwnDroid#74]
Hello, I installed Owndroid with all permissions, Shizuku, and Dhizuku activated. I deleted all other users and disabled all accounts with Hail, and everything is working, despite losing the permission to activate multiple users. I can't install Secure Folder or use Shelter anymore, and the app says this in the info.
![Screenshot_20240907_224109_OwnDroid](https://github.com/user-attachments/assets/bf4b9ca3-f254-4edb-8d4f-f1df5e6e268b)
In ADB, I tried to activate it again, but it didn't do anything. See here:
![Screenshot_20240907_224653_aShell](https://github.com/user-attachments/assets/313e7521-882c-4878-9ef8-8f5923da5c26)
I'm on S23U.
I really don't want to do a reset. This would take more than a few days for me. Maybe you or someone else knows what the problem is. I consider it a bug, but maybe I did/set something wrong. I'm a noob at these things but trying to learn.
(Shelter and secure folder were working before installing and activating Owndroid.)
Thank you.

**Comment by BinTianqi** [comment]
Before you activate OwnDroid, how many users you can create?

**Comment by RedMentos** [comment]
I suggest what's normal with the S23. I had Secure Folder and Shelter active together before, but I never tried anything else. Do you think I should try setting it at that? Do you think I should try setting it the same? I need one with the stock settings of an S23U then to look, I can't find it online.
Thanks for replying.

**Comment by BinTianqi** [comment]
I use LineageOS 21 on OnePlus7, I can create users when OwnDroid is activated, and Maximum supported users is 4.

So, this may be a limitation of OneUI
