### ISSUE TITLE
[Bug] Crash on "Password and keyguard" section

### ISSUE THREAD

**Issue by misakazip** [BinTianqi/OwnDroid#75]
Hello.
I want to set password settings (eg. "Max failed passwords") ,but I can't apply due to crashing...

Device : Xiaomi 11T Pro
OS : HyperOS 1.0 (Android 14)
Device admin : Activated (Dhizuku)
Device owner : Activated (Dhizuku)

**Comment by BinTianqi** [comment]
https://owndroid.pages.dev/Permission.html#dhizuku-api

> Dhizuku restricts some DevicePolicyManager APIs, if you're using Dhizuku mode, OwnDroid may crash when you try to use certain functions. Please don't send feedback when you encounter this issue, unless you are sure it's caused by OwnDroid itself.

Please try to use password-related functions when OwnDroid itself is the Device owner

**Comment by misakazip** [comment]
I tried again and it was solved! I didn't know because I only saw “Issues” on GitHub. I'm sorry, and thank you!
