### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by IzzySoft** [BinTianqi/OwnDroid#77]
At IzzyOnDroid we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). Trying for yours, I was able to successfully generate the APK using `./gradlew assembleRelease`, but the resulting APKs were not identical. The APK (now taken from the v6.0 release) clearly shows it was not built from the commit the tag points to, as it has the hash of the previous commit included with its `version-control-info.textproto`. But it seemingly was not built from that tag either, as there are still differences in the `classes.dex`. My guess is you've built from a "dirty tree" containing changes on top of that (previous) commit, but then added more changes before finally committing – which makes RB rather impossible.

Can you please confirm? And before we're going on: please do not change the existing tag. A new tag with a (maintenance) release however is welcome.

We'd appreciate if you could help making your build reproducible. We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

Looking forward to your reply!

**Comment by BinTianqi** [comment]
OK, I see.

I built v6.0 release APK before I make v6.0 commit, so the reproducible build is not identical. I will make my builds reproducible.

**Comment by BinTianqi** [comment]
I published a new release, [OwnDroid-v6.1.apk](https://github.com/BinTianqi/OwnDroid/releases/download/v6.1/OwnDroid-v6.1.apk)

**Comment by IzzySoft** [comment]
> I published a new release, [OwnDroid-v6.1.apk](https://github.com/BinTianqi/OwnDroid/releases/download/v6.1/OwnDroid-v6.1.apk)

Congrats, that is reproducible! :partying_face:

> I forgot to bump version number, will this apk be published to izzy?

Newer tag with newer file, so yes; that was changed at some point in the past, though I don't really like it, one should never replace what was already distributed. Which means we'll probably change that back at some point in the future.

If you want to avoid that overwrite, you could make a "maintenance release" (e.g. v6.1.1) and attach the updated APK there. I'd very welcome that as it avoids v6.1 being redownloaded each day as it should be an update to the v6.0 the APK claims to be (though checking the timestamp should prevent that, there are sometimes quirks with that). If you can do that within the next 4 hours, it would be in place before the updater kicks in (which it does around 5:15 pm UTC).

That said: Here comes [your RB welcome toot](https://floss.social/@IzzyOnDroid/113373791149720092):

![image](https://github.com/user-attachments/assets/186fb113-3610-47b7-9566-05f507514d5b)

I leave this issue open if you want it as reminder for the maintenance release. Apart from that, I'd say all is done now and the issue can be closed – thanks a lot!

**Comment by BinTianqi** [comment]
v6.0 apk on izzysoft is already overwritten, I won't release v6.1.1, but I will release v6.2 after some new functions are implemented.

**Comment by IzzySoft** [comment]
Yupp, the IoD updater was faster than you :see_no_evil:

**Comment by IzzySoft** [comment]
Hi @BinTianqi, it seems for v6.3, you didn't use the Gradle version specified in your `gradle/wrapper/gradle-wrapper.properties` (currently: 8.9) but another one (according to the `kotlin-tooling-metadata.json` included with your APK, it was 8.10.2). This led to the RB to fail, as the `kotlin-tooling-metadata.json` files differ.

For this release, I've "repaired" it by adjusting `kotlin-tooling-metadata.json` accordingly at the end of the build. But such fixes always require manual intervention – it would be much appreciated if this were not necessary :wink:

**Comment by BinTianqi** [comment]
OwnDroid v6.3 is built with a local gradle installation on my computer, it's version is 8.10.2.  I will use gradle wrapper to build OwnDroid in the future.

**Comment by IzzySoft** [comment]
> it's version is 8.10.2

Yupp, that's what `kotlin-tooling-metadata.json` said and how I [fixed the build](https://codeberg.org/IzzyOnDroid/rbtlog/src/branch/izzy/log/recipes/com.bintianqi.owndroid.yml#L72):

```yaml
- reproducible-apk-tools/inplace-fix.py --internal --zipalign fix-files app/build/outputs/apk/release/app-release-unsigned.apk 'sed s/"8.9"/"8.10.2"/' 'kotlin-tooling-metadata.json'
```

> I will use gradle wrapper to build OwnDroid in the future.

:hugs: Thanks! Recipe [contains a note](https://codeberg.org/IzzyOnDroid/rbtlog/src/branch/izzy/log/recipes/com.bintianqi.owndroid.yml#L5) as reminder this work-around can (hopefully) be removed with the next release. Won't hurt if it stays, but is not needed then anymore. If you say the next release will have it fixed, I'd convert the note to a `FIXME` so I can clean up before the next build starts (`FIXME` prevents automatic processing here).
