### ISSUE TITLE
java.lang.RuntimeException: There must be exactly one installer , when preinstall it into the android system

### ISSUE THREAD

**Issue by sonying** [BinTianqi/OwnDroid#79]
Installation app through adb worked smoothly.
I got this error message and couldn't enter the Android desktop normally when I preinstall the app into AOSP android 12.0
Do you know how to handle this error if I want to preinstall it into the android system?

error message :
01-01 08:00:50.159   714   714 E System  : ************ Failure starting system services
01-01 08:00:50.159   714   714 E System  : java.lang.RuntimeException: There must be exactly one installer; found [ResolveInfo{30e3b7e com.android.packageinstaller/.InstallStart m=0x608000}, ResolveInfo{4a3e8df com.bintianqi.owndroid/.InstallAppActivity m=0x608000}]
01-01 08:00:50.159   714   714 E System  :      at com.android.server.pm.PackageManagerService.getRequiredInstallerLPr(PackageManagerService.java:8651)
01-01 08:00:50.159   714   714 E System  :      at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:8117)
01-01 08:00:50.159   714   714 E System  :      at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:7120)
01-01 08:00:50.159   714   714 E System  :      at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:1166)
01-01 08:00:50.159   714   714 E System  :      at com.android.server.SystemServer.run(SystemServer.java:880)
01-01 08:00:50.159   714   714 E System  :      at com.android.server.SystemServer.main(SystemServer.java:613)
01-01 08:00:50.159   714   714 E System  :      at java.lang.reflect.Method.invoke(Native Method)
01-01 08:00:50.159   714   714 E System  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-01 08:00:50.159   714   714 E System  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
01-01 08:00:50.159   714   714 V SystemServerTiming: StartPackageManagerService took to complete: 1080ms
01-01 08:00:50.160   714   714 E Zygote  : System zygote died with fatal exception
01-01 08:00:50.160   714   714 E Zygote  : java.lang.RuntimeException: There must be exactly one installer; found [ResolveInfo{30e3b7e com.android.packageinstaller/.InstallStart m=0x608000}, ResolveInfo{4a3e8df com.bintianqi.owndroid/.InstallAppActivity m=0x608000}]
01-01 08:00:50.160   714   714 E Zygote  :      at com.android.server.pm.PackageManagerService.getRequiredInstallerLPr(PackageManagerService.java:8651)
01-01 08:00:50.160   714   714 E Zygote  :      at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:8117)
01-01 08:00:50.160   714   714 E Zygote  :      at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:7120)
01-01 08:00:50.160   714   714 E Zygote  :      at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:1166)
01-01 08:00:50.160   714   714 E Zygote  :      at com.android.server.SystemServer.run(SystemServer.java:880)
01-01 08:00:50.160   714   714 E Zygote  :      at com.android.server.SystemServer.main(SystemServer.java:613)
01-01 08:00:50.160   714   714 E Zygote  :      at java.lang.reflect.Method.invoke(Native Method)
01-01 08:00:50.160   714   714 E Zygote  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-01 08:00:50.160   714   714 E Zygote  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
01-01 08:00:50.160   714   714 D AndroidRuntime: Shutting down VM
01-01 08:00:50.160   714   714 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main

**Comment by BinTianqi** [comment]
Try preinstalling [this app](https://github.com/iamr0s/installerx) and see if the issue still exist

**Comment by BinTianqi** [comment]
@sonying If you are still interested in pre-installing OwnDroid, you may try v6.4. I made a new app installer, and it might fix this issue.
