### ISSUE TITLE
Device Management 

### ISSUE THREAD

**Issue by PeterKW** [BinTianqi/OwnDroid#8]
What sort of settings does this allow the user to change that they can't normally?

**Comment by BinTianqi** [comment]
[There is a guide](https://github.com/BinTianqi/AndroidOwner/blob/master/Guide.md). But I wrote it in Chinese. I'm working on a English guide. 

There are some highlited functions, you can only use them after you activate device owner 

- Install or uninstall app
- set a new screen lock password
- create managed users
- disable some function, such as network
- factory reset

**Comment by BinTianqi** [comment]
If you have any question, you can open a new issue or comment below.
