### ISSUE TITLE
Not much to do

### ISSUE THREAD

**Issue by Johngithubandroidpc** [BinTianqi/OwnDroid#81]
Is there a way to use owndroid to grant an Android app device owner privileges, like Icebox, so I don't have to connect my Android 10 phone to a computer for ADB root access? Thank you!

**Comment by BinTianqi** [comment]
Only one device owner can exist on a device.

If you want to share device owner privilege with other app, try https://github.com/iamr0s/dhizuku

**Comment by Johngithubandroidpc** [comment]
> Only one device owner can exist on a device.
> 
> If you want to share device owner privilege with other app, try https://github.com/iamr0s/dhizuku

> This can be achieved by transferring the permissions of OwnDroid to Dhizuku, then enabling Dhizuku mode in OwnDroid, and finally applying the DAX patch to IceBox.

Could you clarify if a factory reset is necessary to activate Owndroid in device owner mode before transferring privileges to Icebox? Or is it possible to enable Owndroid’s device owner mode without resetting, then transfer the privilege to Icebox? I’m currently using Shizuku instead of Dizuku, but it seems that after activating Owndroid, it gets deactivated again when I reopen it from Icebox. Would switching to Dizuku instead of Shizuku help? Thank you Bintuanqi!

**Comment by BinTianqi** [comment]
Not necessary to factory reset.

Dhizuku uses device owner previlege to work, Shizuku uses adb privilege to work, they are not same. You can activate Dhizuku using Shizuku, but you should delete all your account on your device, or freeze them.

**Comment by Johngithubandroidpc** [comment]
> Not necessary to factory reset.
> 
> Dhizuku uses device owner previlege to work, Shizuku uses adb privilege to work, they are not same. You can activate Dhizuku using Shizuku, but you should delete all your account on your device, or freeze them.

That sounds a bit unsettling when you mention deleting all my accounts. Freezing them seems much safer, and I'd prefer not to lose too much of anything. Could you explain how I can freeze my accounts on my Android 10 device? Thank you very much!

**Comment by BinTianqi** [comment]
Freeze the apps who created the accounts.

**Comment by Johngithubandroidpc** [comment]
Hello! Could you please let me know where I can find the DAX patch for Icebox? Thank you!

> > Only one device owner can exist on a device.
> > 
> > If you want to share device owner privilege with other app, try https://github.com/iamr0s/dhizuku
> 
> > This can be achieved by transferring the permissions of OwnDroid to Dhizuku, then enabling Dhizuku mode in OwnDroid, and finally applying the DAX patch to IceBox.
> 
> Could you clarify if a factory reset is necessary to activate Owndroid in device owner mode before transferring privileges to Icebox? Or is it possible to enable Owndroid’s device owner mode without resetting, then transfer the privilege to Icebox? I’m currently using Shizuku instead of Dhizuku, but it seems that after activating Owndroid, it gets deactivated again when I reopen it from Icebox. Would switching to Dhizuku instead of Shizuku help? Thank you BinTianqi!

**Comment by Johngithubandroidpc** [comment]
> Hello! Could you please let me know where I can find the DAX patch for Icebox? Thank you!
> 
> > > Only one device owner can exist on a device.
> > > 
> > > If you want to share device owner privilege with other app, try https://github.com/iamr0s/dhizuku
> > 
> > > This can be achieved by transferring the permissions of OwnDroid to Dhizuku, then enabling Dhizuku mode in OwnDroid, and finally applying the DAX patch to IceBox.
> > 
> > Could you clarify if a factory reset is necessary to activate Owndroid in device owner mode before transferring privileges to Icebox? Or is it possible to enable Owndroid’s device owner mode without resetting, then transfer the privilege to Icebox? I’m currently using Shizuku instead of Dhizuku, but it seems that after activating Owndroid, it gets deactivated again when I reopen it from Icebox. Would switching to Dhizuku instead of Shizuku help? Thank you BinTianqi!
> 
> 

I am now testing this on my other phone, which runs Android 9. I successfully installed both Shizuku and OwnDroid. However, I’m not entirely clear on how to transfer permissions from OwnDroid to Shizuku. Here’s what I’ve done so far:

I managed to get OwnDroid activated as a device admin, but the device owner option remains deactivated. When I try to enable Shizuku within OwnDroid, I get an error message that says "Failed to initiate Shizuku." I was able to activate Shizuku through the Shizuku app itself, but in Shizuku’s settings, the OwnDroid option is still unchecked. I’m not sure if this option should be checked for everything to work properly.

**Comment by BinTianqi** [comment]
To transfer device owner privilege from owndroid to dhizuku, use Transfer ownership in owndroid.
package name: com.rosan.dhizuku
class name: com.rosan.dhizuku.server.DhizukuDAReceiver

**Comment by BinTianqi** [comment]
If freezing accounts not work, you have to delete them.

**Comment by Johngithubandroidpc** [comment]
In short, I finally managed to get both Owndroid and Dhizuku working as device owners. Could you let me know where I can find the DAX patch for Icebox? Thanks!

**Comment by BinTianqi** [comment]
DAX: https://github.com/iamr0s/Dhizuku-API-Xposed/releases/tag/92af06a

LSPatch: https://github.com/LSPosed/LSPatch/releases/tag/v0.6

Patch Icebox yourself.

**Comment by Johngithubandroidpc** [comment]
> DAX: https://github.com/iamr0s/Dhizuku-API-Xposed/releases/tag/92af06a
> 
> LSPatch: https://github.com/LSPosed/LSPatch/releases/tag/v0.6
> 
> Patch Icebox yourself.

My last question. I really appreciate the recommendations you give me for things I can install on my phone! I do have a question, though, about patches or frameworks like Xposed. Do these kinds of tools go against Google Play Store policies? For example, a while back, I got a message from FedEx saying they detected that my phone was rooted through their app, and they blocked me from using it. I had to explain to them that I wasn’t actually using any root. Thanks a lot, BinTianqi!

**Comment by BinTianqi** [comment]
Use LSPatch is ok, google play doesn't care it.

I don't know FedEx detects what, so I can't give you any help on it.

**Comment by Johngithubandroidpc** [comment]
> Use LSPatch is ok, google play doesn't care it.
> 
> I don't know FedEx detects what, so I can't give you any help on it. 

Hi BinTianqi,

I thought I could fix this myself, but I’m stuck with a constant pop-up message saying “System UI has stopped” and “com.android.phone has stopped.” I think this happened because I froze some apps and then rebooted without unfreezing them. I can still see that both OwnDroid and the Dhizuku app have “owner” privileges. Does that mean I might still have a chance to save my phone, or do I need to do a factory reset?

I spent hours yesterday trying to get into my Icebox app, but now, after powering on, I can only see the initial screen. I can’t access any other screens, settings, or apps. When I plug my phone into my computer, ADB can’t detect it either, so I’m unsure of what else to try besides a factory reset. Any suggestions?

Thanks!

**Comment by BinTianqi** [comment]
I'm sorry to hear that. Your phone might be bricked.

If you have a third-party recovery installed, try this: https://xdaforums.com/t/system-and-user-apps-accidentally-frozen.1550205/

**Comment by Johngithubandroidpc** [comment]
> I'm sorry to hear that. Your phone might be bricked.
> 
> If you have a third-party recovery installed, try this: https://xdaforums.com/t/system-and-user-apps-accidentally-frozen.1550205/

Another question I have is whether this Owndroid can grant Shizuku ADB root privileges so I won’t need to connect to my computer each time to enable Shizuku. Thank you very much.
