### ISSUE TITLE
OwnDroid testkey完整激活后应用管理器中权限管理器大部分修改没反应

### ISSUE THREAD

**Issue by LiJiu-gfgfv** [BinTianqi/OwnDroid#82]
设备型号及版本: 
PFGM00_11_C.12
ColorOS 12.1
Android 12
已经使用APatch 10763获取了root
登录了谷歌账号

**Comment by BinTianqi** [comment]
需要目标应用在AndroidManifest中声明使用相关权限

**Comment by LiJiu-gfgfv** [comment]
> 需要目标应用在AndroidManifest中声明使用相关权限
还有一个问题，为什么激活OwnDroid后通过sui面具模块激活的AppOps修改权限也没反应，比如控制设备振动

**Comment by LiJiu-gfgfv** [comment]
OwnDroid_testkey_6.1.apk的版本是6.0是为啥

**Comment by LiJiu-gfgfv** [comment]
激活前是可以正常使用的，用shizuku-root和adb激活状态下都能正常用

**Comment by LiJiu-gfgfv** [comment]
还有个问题，为啥之前这个手机可以正常激活Dhizuku，现在能激活OwnDroid的环境(无任何管理员以及账号)下激活Dhizuku会报错

**Comment by BinTianqi** [comment]
> 还有个问题，为啥之前这个手机可以正常激活Dhizuku，现在能激活OwnDroid的环境(无任何管理员以及账号)下激活Dhizuku会报错

一个设备只能有一个Device owner

>激活前是可以正常使用的，用shizuku-root和adb激活状态下都能正常用

没用过appops，不知道怎么回事

**Comment by LiJiu-gfgfv** [comment]
> > 还有个问题，为啥之前这个手机可以正常激活Dhizuku，现在能激活OwnDroid的环境(无任何管理员以及账号)下激活Dhizuku会报错
> 
> 一个设备只能有一个Device owner
> 
> >激活前是可以正常使用的，用shizuku-root和adb激活状态下都能正常用
> 
> 没用过appops，不知道怎么回事

我指的是可以完整激活OwnDroid的环境但没有激活OwnDroid，尝试激活Dhizuku就报错，然后激活OwnDroid就正常的完整激活

**Comment by BinTianqi** [comment]
> 我指的是可以完整激活OwnDroid的环境但没有激活OwnDroid，尝试激活Dhizuku就报错，然后激活OwnDroid就正常的完整激活

去 https://github.com/iamr0s/dhizuku/issues 问
