### ISSUE TITLE
dhizuku api request

### ISSUE THREAD

**Issue by wentywenty** [BinTianqi/OwnDroid#9]
https://github.com/iamr0s/Dhizuku

dhizuku can share device owner

**Comment by BinTianqi** [comment]
I will start working on it. 

[can you speak chinese](https://github.com/BinTianqi/AndroidOwner/issues/7#issuecomment-2062751437)

**Comment by wentywenty** [comment]
感谢感谢

**Comment by wentywenty** [comment]
目前我测试了
lsposed中dax模块作用于这个软件，可以正常使用
通过lspatch将dax模块修补于这个应用也可以正常使用
![Screenshot_2024-04-19-16-57-23-818_org.lsposed.manager.jpg](https://github.com/BinTianqi/AndroidOwner/assets/63338034/9d72c428-acef-4081-9f9e-7b0449b22435)

![Screenshot_20240419_165744_org.lsposed.lspatch.jpg](https://github.com/BinTianqi/AndroidOwner/assets/63338034/58d8e153-770b-44a9-91ea-be2644761f2a)

![IMG_20240419_165656.jpg](https://github.com/BinTianqi/AndroidOwner/assets/63338034/9840dfd4-c309-4bce-a70e-c592f5e9b0e6)

![Screenshot_2024-04-19-16-57-23-818_org.lsposed.manager.jpg](https://github.com/BinTianqi/AndroidOwner/assets/63338034/3c4ae995-a7ff-44be-9ea7-d6acaa008b1d)

**Comment by wentywenty** [comment]
但是会出现第二个选项激活不了的情况![IMG_20240419_165656.jpg](https://github.com/BinTianqi/AndroidOwner/assets/63338034/c408e99f-1a6f-44ea-ab6e-14742e3e5d9b)


在ashell you
https://github.com/DP-Hridayan/aShellYou
中执行对应命令后出现以下输出

![Screenshot_2024-04-19-17-00-12-527_in.hridayan.ashell.jpg](https://github.com/BinTianqi/AndroidOwner/assets/63338034/3903e9a0-bc7f-4747-a18d-44ee311495ad)

**Comment by wentywenty** [comment]
感谢作者大大，辛苦了！！！

**Comment by BinTianqi** [comment]
第一次知道有dax这个模块😀

**Comment by BinTianqi** [comment]
profile owner和device owner不能同时存在。

直接激活profile owner没什么用，它是给工作资料和managed user（“用户管理”中创建的用户）用的

**Comment by BinTianqi** [comment]
### 很抱歉我不能给OwnDroid用上Dhizuku-API

[Dhizuku-API](https://github.com/iamr0s/Dhizuku-API/)一共有三种接口：

- Binder wrapper
  调用了系统的隐藏API，不稳定
- User service
  bug太多。我在OwnDroid调用他的API，竟然会让Dhizuku崩溃，十分不稳定
- Delegated scope
  安卓官方功能，稳定但功能极少

这三个接口都很难用，所以这个功能还是不做了吧
